---
title: "publications"
---

## Stream of Data Consciousness
[Stream of data consciousness](https://www.mdt-datascience.com/) blog is a collection of data analysis. 
Each post represents a serious tentative to answer relevant questions (at least for the author) through data science.

Posts are not always an easy read: while the industry follow the path called "democratize" data science, content posted assumes readers have a certain degree of data science awareness.

This blog project has been active from March 2020 up to October 2021 but it is currently considered closed. 

## Computing Matrix Algebra
*Nobody can be a poet without feeling strong affection for words, at the same time nobody can be serious about data science without becoming close friend to matrices.*

Computing Matrix Algebra is actually a cheat sheet about computing matrix algebra operations such as matrix multiplication, inversion and factorization.

It is written foR (aspiring) data scientists where with "foR" (capital letter R) it is meant the side of data science addicted to R and its gorgeous ecosystem especially including Rcpp, RcppArmadillo and RcppEigen.

It was written taking advantage of the stay-at-home policy during the COVID outbreak and published in April 2020 on [Leanpub](https://leanpub.com/computingmatrixalgebra).

In January 2023 the booklet became an interactive course published by [educative](https://www.educative.io/collection/10370001/4727811482320896).

## on war: a mathematical and computational perspective

[On War](https://mdt-ds.github.io/on_war/) is a short essay suggesting how to think about conflicts using mathematical modeling by taking advantage of the foundations of game theory, Markovian processes and system dynamics.

It can be read on several levels: as a compendium of mathematical modeling related to war and as a suggestion to shift the focus of war analysis from geopolitics to the inner workings of war itself.
